copy HttpServer\HttpServer.Logging\bin\Release\HttpServer.Logging.dll bin
copy HttpServer\HttpServer.Main\bin\Release\HttpServer.Main.dll bin
copy HttpServer\HttpServer.StaticFileServer\bin\Release\HttpServer.StaticFileServer.exe bin
copy HttpServer\HttpServer.StaticFileServer\bin\Release\directory.html bin
copy HttpServer\HttpServer.StaticFileServer\bin\Release\error.html bin
copy HttpServer\HttpServer.StaticFileServer\bin\Release\notFound.html bin
copy HttpServer\HttpServer.WebServer\bin\Release\HttpServer.WebServer.dll bin
copy HttpServer\HttpServer.WebServer\bin\Release\Newtonsoft.Json.dll bin
copy HttpServer\HttpServer.WebServer.Test\bin\Release\HttpServer.WebServer.Test.exe bin